### PR TITLE
added comment to layouts/reusable/MobileNav.tsx

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by seniordev0207 — COMMENTED** [review]
Great!

**Review by onlinehub0808 — COMMENTED** [review]
done

**Review by onlinehub88 — COMMENTED** [review]
reviewed

**Review by FamousTiger — COMMENTED** [review]
Perfect

**Review by ghost — COMMENTED** [review]
Ok

**Review by codefoundry140 — COMMENTED** [review]
done

**Pull request merged**
