### PR TITLE
added comment to layouts/engine/index.tsx

### PR DESCRIPTION
**Pull request by FamousTiger**

### CODE REVIEW

**Review by seniordev0207 — COMMENTED** [review]
Done.

**Review by onlinehub0808 — COMMENTED** [review]
done

**Review by onlinehub88 — COMMENTED** [review]
reviewed

**Review by FamousTiger — COMMENTED** [review]
Perfect

**Review by ghost — COMMENTED** [review]
Ok

**Review by codefoundry140 — COMMENTED** [review]
done

**Pull request merged**
